version: "3.9"
services:
  api:
    build: ./api
    ports:
      - "3000:3000"
  shell:
    build: ./shell
    ports:
      - "3001:3001"
    depends_on:
      - remote
      - api
  remote:
    build: ./remote
    ports:
      - "3002:3002"